[package]
name = "distributed-key-generation"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "key_generator"
path = "src/bin/key_generator.rs"

[dependencies]
bincode = "1.3.3"
tokio = { version = "1.37.0", features = ["full"] }

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.127"

clap = { version = "4.4.7", features = ["derive"] }
toml = "0.8.13"

tracing = "0.1.37"
tracing-subscriber = "0.3.17"

skde = { git = "https://github.com/radiusxyz/skde", rev="f8417e3611f58b7d38a85f209279d096efe0a378"}

radius-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", features = ["full"], rev="1e645cce57dfc6498bf381a702023c9f1aa2d8a5" }