[package]
name = "distributed-key-generation"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "key-generator"
path = "src/bin/key_generator.rs"

[dependencies]
bincode = "1.3.3"
tokio = { version = "1.37.0", features = ["full"] }

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.127"

clap = { version = "4.4.7", features = ["derive"] }
toml = "0.8.13"

tracing = "0.1.37"
tracing-subscriber = "0.3.17"

skde = { git = "https://github.com/radiusxyz/skde", rev="13f18a4a6846795bb0ca20c4cd5ad494b7b6444f"}

radius-sdk = { git = "https://github.com/radiusxyz/radius-sdk-rs", features = ["json-rpc", "kvstore-json", "signature"], rev="df4b24469a221b2e084ca8255cef1223ebba538e" }

