# Set external rpc url
external_rpc_url = "http://127.0.0.1:3000"

# Set internal rpc url
internal_rpc_url = "http://127.0.0.1:4000"

# Set cluster rpc url
cluster_rpc_url = "http://127.0.0.1:5000"

# Set seeder rpc url
seeder_rpc_url = "http://127.0.0.1:6000"

